version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client
      - npm install

  build:
    commands:
      - pwd           # Print current working directory
      - ls -al        # List contents of current directory
      - cd client     # Navigate to the client directory
      - npm install                        # Install dependencies
      - echo "Running npm run build..."
      - npm run build                      # Your build command
      - echo "Build completed!"

  pre_build:
    commands:
      - npm run build