version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
  pre_build:
    commands:
      - cd client
      - npm install
      - cd ../server
      - npm install
  build:
    commands:
      - cd client
      - npm run build
      - cd ../server
      - npm run dev
