version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client
      - npm install
      - cd ../server
      - npm install

  pre_build:
    commands:
      - cd ../client
      - npm run build

artifacts:
  files:
    - client/dist/**/*
