version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - cd client
      - npm install

  build_client:
    commands:
      - cd client
      - npm run build

  build_server:
    commands:
      - cd ../server
      - npm install

artifacts:
  files:
    - client/build/**/*
