version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client
      - npm install

  build:
    commands:
      - cd client
      - npm install
      - echo "Running npm run build..."
      - npm run build
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'
