version: '3.9'
services:
  postgres:
    image: postgres:14.1
    container_name: teamcdatabase
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: teamcdatabase
      POSTGRES_PASSWORD: teamcdatabase
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  pgadmin:
    container_name: zealous_swanson
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
